POST http://localhost:8080/api/instruments
Content-Type: application/json

{
"name": "yahama",
  "type": "ppp",
  "price": 220000
}

###
GET http://localhost:8080/api/instruments
Content-Type: application/json